SFDCPrj/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

LeaveManagement/force-app/main/default/objects/Employee__c/fields/Employee_User_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Employee_User_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee User Lookup</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

LeaveManagement/force-app/main/default/objects/Employee__c/fields/Leave__c.field-meta.xml
<CustomField>
    <fullName>Leave__c</fullName>
    <label>Leave Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LeaveManagement/force-app/main/default/objects/Leave__c/Leave__c.object-meta.xml
<CustomObject>
    <label>Leave</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LeaveManagement/force-app/main/default/classes/EmployeeTriggerHandler.cls
public class EmployeeTriggerHandler {
    public static void beforeInsert(List<Employee__c> triggernew){
        map<Id,Id> mapEmpIdsUserId = new map<id,id>();
        for(Employee__c objEmp : triggernew){
            if(objEmp.Date_of_Joining__c != null){
                Date dtJoiningDate = objEmp.Date_of_Joining__c;
       		Date dtEndYearDate = date.newInstance(dtJoiningDate.Year(),12,31);
        	Integer dy = dtJoiningDate.day();
        	Integer months;
        	months =dtJoiningDate.monthsBetween(dtEndYearDate); 
        	if(dy<15){
          	objEmp.Leave__c = (months*2)+2;  
        	}else{
            	objEmp.Leave__c = months*2;
        	}
       	mapEmpIdsUserId.put(objEmp.Id,objEmp.Employee_User_Lookup__c);
                
            }
            
    	}  
    }
    
    
    public static void afterInsert(List<Employee__c> triggernew){
         map<Id,Id> mapEmpIdsUserId = new map<id,id>();
        for(Employee__c objEmp : triggernew){
            mapEmpIdsUserId.put(objEmp.Id,objEmp.Employee_User_Lookup__c);
    	}  
        List<Employee__Share> lstempShare = new List<Employee__Share>();
        for(Employee__c objEmp : triggernew){
            Employee__Share objEmpShare  = new Employee__Share();
        	objEmpShare.AccessLevel ='edit';
        	objEmpShare.ParentId = objEmp.id; 
        	objEmpShare.UserOrGroupId  = mapEmpIdsUserId.get(objEmp.id);
        	lstempShare.add(objEmpShare);
    	}
    }

}